apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-opgave
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zafer2203/Git-demo-projekt.git'
    targetRevision: main
    path: ArgoCD-opgave
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true