apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-opgave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-opgave
  template:
    metadata:
      labels:
        app: argocd-opgave
    spec:
      containers:
      - name: argocd-opgave
        image: ghcr.io/zafer2203/argocd-opgave:latest
        imagePullPolicy: Always