apiVersion: apps/v1
kind: Deployment
metadata:
  name: ArgoCD-opgave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ArgoCD-opgave
  template:
    metadata:
      labels:
        app: ArgoCD-opgave
    spec:
      containers:
      - name: ArgoCD-opgave
        image: ghcr.io/zafer2203/ArgoCD-opgave:latest
        imagePullPolicy: Always