name: Byg docker image

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: write

      steps:
         - uses: actions/checkout@v4

         - name: log in to github container registry
           run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

         - name: build and push docker image
           run: docker build -t ghcr.io/${{ github.repository_owner }}/hello-kubernetes:latest ./HelloWorldKubernetes

         - name: run docker image (detached mode)
           run: docker run -d ghcr.io/${{ github.repository_owner }}/hello-kubernetes:latest

         - name: push docker image to registry
           run: docker push ghcr.io/${{ github.repository_owner }}/hello-kubernetes:latest

